version: '3'
services:
  llm:
    container_name: llm_api
    build: ./llm
    ports:
      - 8085:8085
    environment:
      - API_PORT=8085
      - LLM_API=https://randomly-excited-gnat.ngrok-free.app
    volumes:
      - ./llm:/opt/app
    networks:
    - ai-network

  ui:
    container_name: streamlit
    build: ./streamlit
    ports:
      - 8501:8501
    environment:
      - DATASET=/opt/app/data.csv
      - LLM_API=http://llm_api:8085
      - DB_API=http://pgvector-api:8080
      - TRANSLATOR=http://translator-api:8090
      - HOST=pgvector
      - USER=admin
      - PASSWORD=admin
    volumes:
      - ./streamlit:/app
    networks:
    - ai-network

  pgvector:
    container_name: pgvector
    image: ankane/pgvector
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - ai-network

  pgvector-api:
    container_name: pgvector-api
    build: ./pg_vector_api
    ports:
      - 8080:8080
    environment:
      - HOST=pgvector
      - USER=admin
      - PASSWORD=admin
    volumes:
      - ./pg_vector_api:/app
    networks:
    - ai-network

  translator-api:
    container_name: translator-api
    build: ./translator
    ports:
      - 8090:8090
    volumes:
      - ./translator:/app
    networks:
    - ai-network

networks:
    ai-network: